name: Build Binaries
on:
  release:
    types: [ published ]
jobs:
  build-unix:
    strategy:
      matrix:
        os: [ ubuntu, macos ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build binaries
        run: go build -o jira-attachment-migrator
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jira-attachment-migrator-${{ matrix.os }}
          path: ./jira-attachment-migrator*
      - name: Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          zip jira-attachment-migrator-${{ matrix.os }}.zip jira-attachment-migrator
          gh release upload $(echo ${{ github.ref }} | cut -d '/' -f3) jira-attachment-migrator-${{ matrix.os }}.zip
  build-windows:
    strategy:
      matrix:
        os: [ windows ]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build binaries
        run: go build -o jira-attachment-migrator.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jira-attachment-migrator-${{ matrix.os }}
          path: ./jira-attachment-migrator*
      - name: Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $compress = @{
            Path = "jira-attachment-migrator.exe"
            CompressionLevel = "Fastest"
            DestinationPath = "jira-attachment-migrator-windows.zip"
          }
          Compress-Archive @compress
          gh release upload $(echo ${{ github.ref }} | cut -d '/' -f3) jira-attachment-migrator-windows.zip
